Change Tier0 to be boolean and added a Tier0_type for raid type

diff --git a/modules/clients/scripts/user_data_rocky.sh.tmpl b/modules/clients/scripts/user_data_rocky.sh.tmpl
--- a/modules/clients/scripts/user_data_rocky.sh.tmpl
+++ b/modules/clients/scripts/user_data_rocky.sh.tmpl
@@ -20,10 +20,14 @@ sudo dnf install -y python3-pip git bc nfs-utils screen net-tools fio
 # DO NOT MODIFY ANYTHING BELOW THIS LINE OR INSTANCES MAY NOT START CORRECTLY!
 # ----------------------------------------------------------------------------
 
-TARGET_USER="%[1]s"
-TARGET_HOME="%[2]s"
-SSH_KEYS="%[3]s"
-TIER0="%[4]s"
+TARGET_USER='${TARGET_USER}'
+TARGET_HOME='${TARGET_HOME}'
+SSH_KEYS='${SSH_KEYS}'
+ALLOW_ROOT='${ALLOW_ROOT}'
+TIER0='${TIER0}'
+TIER0_TYPE='${TIER0_TYPE}'
+ROOT_USER='${ROOT_USER}'
+ROOT_HOME='/${ROOT_USER}'
 
 # Get rid of fingerprint checking on ssh
 # We need this in case somebody wants to run automated scripts. Otherwise,
@@ -34,11 +38,14 @@ sudo tee -a /etc/ssh/ssh_config > /dev/null <<'EOF'
     StrictHostKeyChecking no
     UserKnownHostsFile /dev/null
 EOF
+sudo tee -a /etc/ssh/sshd_config > /dev/null <<'EOF'
+    PermitRootLogin yes
+    PubkeyAuthentication yes
+EOF
 
-# Build NFS mountpoint
+# Restart the sshd
 
-sudo mkdir -p /mnt/nfs-test
-sudo chmod 777 /mnt/nfs-test
+systemctl restart ssh
 
 # SSH Key Management
 
@@ -58,10 +65,39 @@ if [ -n "$${SSH_KEYS}" ]; then
     chown -R "$${TARGET_USER}:$${TARGET_USER}" "$${TARGET_HOME}/.ssh"
 fi
 
+# --- SSH Key Management for additional keys (This is ONLY for root) ---
+
+if [ -n "$${SSH_KEYS}" ] && [ "$${ALLOW_ROOT}" = "true" ]; then
+    echo "Starting SSH Key Management Deployment for $${ROOT_USER}"
+
+    if [ ! -d "$${ROOT_HOME}/.ssh" ]; then
+      mkdir -p "$${ROOT_HOME}/.ssh"
+      chmod 700 "$${ROOT_HOME}/.ssh"
+      touch "$${ROOT_HOME}/.ssh/authorized_keys"
+    fi
+    
+    # Process keys line by line
+    
+    echo "$${SSH_KEYS}" | while read -r key; do
+        if [ -n "$${key}" ] && ! grep -qF "$${key}" "$${ROOT_HOME}/.ssh/authorized_keys"; then
+            echo "$${key}" >> "$${ROOT_HOME}/.ssh/authorized_keys"
+        fi
+    done
+
+    chmod 600 "$${ROOT_HOME}/.ssh/authorized_keys"
+    chown -R "$${ROOT_USER}":"$${ROOT_USER}" "$${ROOT_HOME}/.ssh"
+    echo "Ending SSH Key Management Deployment for $${ROOT_USER}"
+fi
+
+# Build NFS mountpoint
+
+sudo mkdir -p /mnt/nfs-test
+sudo chmod 777 /mnt/nfs-test
+
 # If Tier0 is enabled, then work on the nvme drives
 
-if [ -n "${TIER0}" ]; then
-    echo "Tier0 is enabled (${TIER0}). Installing mdadm & detecing NVMe..."
+if [ "${TIER0}" = "ture" ]; then
+    echo "Tier0 is enabled. Installing mdadm & detecing NVMe..."
 
     # Load packages needed for Tier0
 
@@ -86,7 +122,7 @@ if [ -n "${TIER0}" ]; then
 
     TOTAL_DEVICES="${#NVME_DEVICES[@]}"
 
-    case "${TIER0}" in
+    case "${TIER0_TYPE}" in
     raid-0)
         MIN_REQUIRED=2
         raid_options="--level=0 --raid-devices=${TOTAL_DEVICES}"
@@ -100,19 +136,19 @@ if [ -n "${TIER0}" ]; then
         raid_options="--level=6 --raid-devices=${TOTAL_DEVICES}"
         ;;
       *)
-        echo "Error: Invalid TIER0 value '${TIER0}'." >&2
+        echo "Error: Invalid TIER0 value '${TIER0_TYPE}'." >&2
         exit 1
         ;;
     esac
 
     if [ "${TOTAL_DEVICES}" -lt "${MIN_REQUIRED}" ]; then
-        echo "Error: Insufficient devices (${TOTAL_DEVICES}) for ${TIER0} (needs ≥${MIN_REQUIRED}). Skipping."
+        echo "Error: Insufficient devices (${TOTAL_DEVICES}) for ${TIER0_TYPE} (needs ≥${MIN_REQUIRED}). Skipping."
         exit 1
     fi
 
     # Build the RAID device
 
-    RAID_NUM="${TIER0#raid-}"
+    RAID_NUM="${TIER0_TYPE#raid-}"
     echo "Creating RAID${RAID_NUM} on ${TOTAL_DEVICES} devices…"
     sudo mdadm --create --verbose /dev/md0 \
      ${raid_options} ${NVME_DEVICES[*]}
@@ -167,5 +203,4 @@ else
 fi
 
 # Reboot
-
 sudo reboot
